/**
 * @file ccu4_slice_config.h
 * @date 2016-06-21
 *
 * NOTE:
 * This file is generated by DAVE-4. Any manual modification done to this file will be lost when the code is regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * CCU4_SLICE_CONFIG v4.0.16 - Configures the properties of CCU4 timer.
 * Copyright (c) 2015-2017, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG (dave@infineon.com).
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 *
 * 2016-02-05:
 *     - Initial version<br>
 *
 * 2016-06-21:
 *     - First productive version
 *
 * 2016-07-20:
 *     - UI is changed and code generation issues are fixed.
 *
 * @endcond
 *
 */


#ifndef CCU4_SLICE_CONFIG_H
#define CCU4_SLICE_CONFIG_H

#include "ccu4_slice_config_conf.h"
#include "xmc_ccu4.h"

#if (!((XMC_LIB_MAJOR_VERSION == 2U) && \
     (XMC_LIB_MINOR_VERSION >= 1U) && \
     (XMC_LIB_PATCH_VERSION >= 8U)))
#error "CCU4_SLICE_CONFIG requires XMC Peripheral Library v2.1.8 or higher"
#endif

/**********************************************************************************************************************
* ENUMS
**********************************************************************************************************************/
 /**
  * @ingroup CCU4_SLICE_CONFIG_enumerations
  * @{
  */

/**
 *   @brief The type identifies the APP status.
 */
typedef enum CCU4_SLICE_CONFIG_STATUS
{
  /**
  * STATUS SUCCESS
  */
  CCU4_SLICE_CONFIG_STATUS_SUCCESS = 0,

  /**
  * STATUS FAILURE
  */
  CCU4_SLICE_CONFIG_STATUS_FAILURE,

} CCU4_SLICE_CONFIG_STATUS_t;

/**
 * @}
 */
/**********************************************************************************************************************
* DATA STRUCTURES
**********************************************************************************************************************/
/**
  * @ingroup CCU4_SLICE_CONFIG_datastructures
  * @{
  */

/**
 * @brief Configuration parameters of the CCU4_SLICE_CONFIG APP
 */

/**
 * @brief Instance CCU4_SLICE_CONFIG_t
 */

typedef struct CCU4_SLICE_CONFIG
{
  CCU4_SLICE_CONFIG_STATUS_t (*init)(void); /**< Defines the local initialization function for the instance */
  GLOBAL_CCU4_t *global; /**< Pointer to required GLOBAL_CCU4 APP */
  XMC_CCU4_SLICE_t *slice_ptr; /**< CCU4x_CC4y slice pointer */
  uint8_t slice_num; /**< slice number */
} CCU4_SLICE_CONFIG_t;

/**
 * @}
 */

/**
 * @ingroup CCU4_SLICE_CONFIG_apidoc
 * @{
 */

/***********************************************************************************************************************
 * API Prototypes
 **********************************************************************************************************************/
/* Support for C++ */

#ifdef __cplusplus
extern "C" {
#endif
/**
 * @brief Retrieves the version of the CCU4_SLICE_CONFIG APP.
 * @param None
 * @return DAVE_APP_VERSION_t APP version information (major, minor and patch number)
 *
 * \par<b>Description: </b><br>
 * The function can be used to check application software compatibility with a specific version of the APP.
 *
 *Example Usage:
 *
 * @code
  #include <DAVE.h>

  int main(void)
  {
    DAVE_APP_VERSION_t version;
    version = CCU4_SLICE_CONFIG_GetAppVersion();
    while(1);
    return 0;
  }
 * @endcode
 */
DAVE_APP_VERSION_t CCU4_SLICE_CONFIG_GetAppVersion(void);

/**
 * @brief Initializes the CCU4_SLICE_CONFIG APP.
 * @param  handle_ptr Instance of CCU4_SLICE_CONFIG_t APP
 * @return CCU4_SLICE_CONFIG_STATUS_t
 *
 * \par<b>Description: </b><br>
 * Configures the CCU4 slice registers with the selected CCU4_SLICE_CONFIG parameters.
 *
 * Example Usage:
 * @code
  #include <DAVE.h>

  int main(void)
  {
   DAVE_Init(); //CCU4_SLICE_CONFIG_Init() is called by DAVE_Init().
    while(1);
    return 0;
  }
 * @endcode
 */
CCU4_SLICE_CONFIG_STATUS_t CCU4_SLICE_CONFIG_Init(const CCU4_SLICE_CONFIG_t *const handle_ptr);

/* Include App extern declaration file */
#include "ccu4_slice_config_extern.h"

/**
 * @}
 */
#ifdef __cplusplus
}
#endif
#endif /* CCU4_SLICE_CONFIG_H_ */


